package Tugas6.view;

import javax.swing.*;
import Tugas6.logika.AplikasiCekCuacaHelper;
import javax.swing.table.DefaultTableModel;

public class AplikasiCekCuacaSederhanaFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AplikasiCekCuacaSederhanaFrame.class.getName());

    /**
     * Creates new form AplikasiCekCuacaSederhanaFrame
     */
    public AplikasiCekCuacaSederhanaFrame() {
        initComponents();
        DefaultTableModel model = (DefaultTableModel) jTableHistory.getModel();
        jButtonCuaca.addActionListener(e -> {
        String kota = jTextKota.getText().trim();
        if (kota.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Masukkan nama kota!");
            return;
        }
        String data = AplikasiCekCuacaHelper.ambilDataCuaca(kota);
        if (data != null) {
            AplikasiCekCuacaHelper.tampilkanCuaca(data, jLabelKondisi, jLabelSuhu, jPanelGambar);
            AplikasiCekCuacaHelper.tambahKeTabel(model, kota, data);
    }
        });

        jButtonFavorit.addActionListener(e -> {
            String kota = jTextKota.getText().trim();
            if (!kota.isEmpty() && ((DefaultComboBoxModel<String>) jFavorit.getModel()).getIndexOf(kota) == -1) {
                jFavorit.addItem(kota);
            }
        });

        jButtonSimpanCSV.addActionListener(e -> {
            AplikasiCekCuacaHelper.simpanCSV(model);
        });

        jButtonMuatCSV.addActionListener(e -> {
            AplikasiCekCuacaHelper.muatCSV(model);
        });

        jFavorit.addItemListener(e -> {
            if (e.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
                jTextKota.setText(jFavorit.getSelectedItem().toString());
            }
        });
            }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        NamaKota = new javax.swing.JLabel();
        jButtonCuaca = new javax.swing.JButton();
        jTextKota = new javax.swing.JTextField();
        jButtonFavorit = new javax.swing.JButton();
        jFavorit = new javax.swing.JComboBox<>();
        jButtonMuatCSV = new javax.swing.JButton();
        jButtonSimpanCSV = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jPanelGambar = new javax.swing.JPanel();
        jLabelKondisi = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabelSuhu = new javax.swing.JLabel();
        jScrollTabel = new javax.swing.JScrollPane();
        jTableHistory = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplikasi Cek Cuaca Sederhana");

        jPanel4.setBackground(new java.awt.Color(255, 223, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "Applikasi Cek Cuaca Sederhana", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 18)), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP)); // NOI18N

        NamaKota.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        NamaKota.setText("Masukkan Nama Kota");

        jButtonCuaca.setBackground(new java.awt.Color(255, 204, 153));
        jButtonCuaca.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButtonCuaca.setText("Cek Cuaca");
        jButtonCuaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCuacaActionPerformed(evt);
            }
        });

        jTextKota.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        jButtonFavorit.setBackground(new java.awt.Color(255, 204, 153));
        jButtonFavorit.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButtonFavorit.setText("Tambahkan Kota Favorit");

        jFavorit.setBackground(new java.awt.Color(204, 204, 255));
        jFavorit.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        jButtonMuatCSV.setBackground(new java.awt.Color(255, 204, 153));
        jButtonMuatCSV.setText("Muat Ke CSV");

        jButtonSimpanCSV.setBackground(new java.awt.Color(255, 204, 153));
        jButtonSimpanCSV.setText("Simpan Ke CSV");

        jPanelGambar.setBackground(new java.awt.Color(255, 255, 255));

        jLabelKondisi.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabelKondisi.setText("Kondisi :");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("||");

        jLabelSuhu.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabelSuhu.setText("Suhu :");

        javax.swing.GroupLayout jPanelGambarLayout = new javax.swing.GroupLayout(jPanelGambar);
        jPanelGambar.setLayout(jPanelGambarLayout);
        jPanelGambarLayout.setHorizontalGroup(
            jPanelGambarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGambarLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabelKondisi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(43, 43, 43)
                .addComponent(jLabelSuhu)
                .addGap(87, 87, 87))
        );
        jPanelGambarLayout.setVerticalGroup(
            jPanelGambarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGambarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelGambarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSuhu)
                    .addComponent(jLabelKondisi)
                    .addComponent(jLabel7))
                .addContainerGap(178, Short.MAX_VALUE))
        );

        jScrollPane3.setViewportView(jPanelGambar);

        jTableHistory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kota", "Cuaca"
            }
        ));
        jScrollTabel.setViewportView(jTableHistory);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jFavorit, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(398, 398, 398))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(NamaKota))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jButtonSimpanCSV)
                        .addGap(189, 189, 189)
                        .addComponent(jButtonMuatCSV))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonCuaca, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextKota, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonFavorit, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollTabel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(103, 103, 103))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NamaKota)
                    .addComponent(jTextKota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonCuaca)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonFavorit)
                    .addComponent(jFavorit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(78, 78, 78)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jScrollTabel, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonMuatCSV)
                            .addComponent(jButtonSimpanCSV)))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 811, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCuacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCuacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCuacaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AplikasiCekCuacaSederhanaFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel NamaKota;
    private javax.swing.JButton btnCek;
    private javax.swing.JButton btnCek1;
    private javax.swing.JButton btnCek2;
    private javax.swing.JButton btnFavorit;
    private javax.swing.JButton btnFavorit1;
    private javax.swing.JButton btnFavorit2;
    private javax.swing.JComboBox<String> cmbKotaFavorit;
    private javax.swing.JComboBox<String> cmbKotaFavorit1;
    private javax.swing.JComboBox<String> cmbKotaFavorit2;
    private javax.swing.JButton jButtonCuaca;
    private javax.swing.JButton jButtonFavorit;
    private javax.swing.JButton jButtonMuatCSV;
    private javax.swing.JButton jButtonSimpanCSV;
    private javax.swing.JComboBox<String> jFavorit;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelKondisi;
    private javax.swing.JLabel jLabelSuhu;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanelGambar;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollTabel;
    private javax.swing.JTable jTableHistory;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextKota;
    private javax.swing.JLabel txtHasilCuaca;
    private javax.swing.JLabel txtHasilCuaca1;
    private javax.swing.JLabel txtHasilCuaca2;
    private javax.swing.JLabel txtKota;
    private javax.swing.JLabel txtKota1;
    private javax.swing.JLabel txtKota2;
    private javax.swing.JLabel txtKotaFavorit;
    private javax.swing.JLabel txtKotaFavorit1;
    private javax.swing.JLabel txtKotaFavorit2;
    // End of variables declaration//GEN-END:variables
}
